### ISSUE TITLE
サインアップ時のエラー

### ISSUE THREAD

**Issue by YuzuRyo61** [syuilo/kiwi#16]
![image](https://user-images.githubusercontent.com/18282413/58870927-109b3b00-86fc-11e9-90d6-a13f2b06aea9.png)

フォーム及びreCAPTCHA認証は全て行っている状態で送信すると以上のようなエラーが出る

**Comment by u1-liquid** [comment]
FYI: https://misskey.io/notes/7tkziwbvhi
> あー、名前は a-z0-9_ が使えます

**Comment by YuzuRyo61** [comment]
（大文字でも登録できるようにしたほうがいいなーって思う私です）
