### ISSUE TITLE
ページ編集中, 作成中にページ離脱しそうになった時に警告を表示してほしい

### ISSUE THREAD

**Issue by nzws** [syuilo/kiwi#17]
タブ間違えて消して30分くらいのデータが消えた時のかなしみ

***

これ
![image](https://user-images.githubusercontent.com/14953122/58876153-375f6e80-8708-11e9-84a3-6af5ac58870c.png)

**Comment by marihachi** [comment]
これはめっちゃ分かるのでぜひほしい
